import json
import time
from pathlib import Path
from typing import Dict
from rules.rule_engine import RuleEngine
from scanner.scanner   import Scanner

HANDOFF_DIR = Path(".clockwork/handoff")
HANDOFF_LOG = Path(".clockwork/handoff_log.json")

class HandoffCommand:
    def __init__(self, settings, state, context):
        self.settings = settings
        self.state    = state
        self.context  = context

    def execute(self, handoff_to: str = "next_agent"):
        print("[Handoff] Generating handoff package...")
        self.state.emit_event("handoff_started", {"to": handoff_to})
        HANDOFF_DIR.mkdir(parents=True, exist_ok=True)

        print("[Handoff] Step 1: Validating system state...")
        repo_map = {}
        try:
            scanner  = Scanner(root=".")
            repo_map = scanner.run()
        except Exception as e:
            print("[Handoff] Scanner warning: " + str(e))

        ctx    = self.context.snapshot()
        arch   = self.context.get_architecture()
        tasks  = self.context.get_next_tasks()
        skills = self.context.get_skills()
        hist   = self.context.get_history()[-10:]

        print("[Handoff] Step 2: Building handoff package...")
        handoff: Dict = {
            "meta": {
                "generated_at": time.time(),
                "handoff_to":   handoff_to,
                "mode":         self.settings.mode,
                "version":      "2.0",
            },
            "project":        ctx.get("project", {}),
            "architecture":   arch,
            "current_state":  ctx.get("context_state", {}).get("summary", ""),
            "next_tasks":     tasks,
            "skills_required":skills,
            "rules_reference":".clockwork/rules.yaml",
            "dependencies":   ctx.get("repository", {}).get("dependencies", []),
            "context_snapshot": {
                "languages":  ctx.get("repository", {}).get("languages", {}),
                "frameworks": ctx.get("repository", {}).get("frameworks", []),
                "components": ctx.get("repository", {}).get("components", {}),
            },
            "recent_history":  hist,
            "risk_level":      "low",
            "execution_status":self.state.snapshot().get("healthy", True),
        }

        handoff_json = HANDOFF_DIR / "handoff.json"
        with open(handoff_json, "w") as f:
            json.dump(handoff, f, indent=2)

        print("[Handoff] Step 3: Writing agent brief...")
        brief      = self._generate_brief(handoff)
        brief_path = HANDOFF_DIR / "next_agent_brief.md"
        brief_path.write_text(brief, encoding="utf-8")

        print("[Handoff] Step 4: Logging handoff...")
        self._log_handoff(handoff_to, tasks)

        self.state.emit_event("handoff_completed", {"to": handoff_to, "tasks": len(tasks)})
        print("[Handoff] Package ready at: " + str(HANDOFF_DIR))
        return handoff

    def _generate_brief(self, handoff: Dict) -> str:
        tasks_str  = "\n".join("- " + t for t in handoff.get("next_tasks", []))
        skills_str = ", ".join(handoff.get("skills_required", []))
        deps       = handoff.get("dependencies", [])
        deps_str   = ", ".join(d.get("name","") for d in deps[:10])
        return (
            "# Clockwork Agent Handoff Brief\n\n"
            "## Project\n" + str(handoff.get("project",{}).get("name","Unknown")) + "\n\n"
            "## Architecture\n" + str(handoff.get("architecture","unknown")) + "\n\n"
            "## Current State\n" + str(handoff.get("current_state","")) + "\n\n"
            "## Next Tasks\n" + (tasks_str or "- No pending tasks defined") + "\n\n"
            "## Skills Required\n" + (skills_str or "Not specified") + "\n\n"
            "## Dependencies\n" + (deps_str or "None detected") + "\n\n"
            "## Rules Reference\n" + handoff.get("rules_reference",".clockwork/rules.yaml") + "\n\n"
            "## Execution Mode\n" + handoff.get("meta",{}).get("mode","safe") + "\n\n"
            "---\n_Generated by Clockwork AI OS_\n"
        )

    def _log_handoff(self, handoff_to: str, tasks: list):
        HANDOFF_LOG.parent.mkdir(parents=True, exist_ok=True)
        log = []
        if HANDOFF_LOG.exists():
            with open(HANDOFF_LOG) as f:
                log = json.load(f)
        log.append({"timestamp": time.time(), "handoff_to": handoff_to, "task": str(tasks[:3])})
        with open(HANDOFF_LOG, "w") as f:
            json.dump(log, f, indent=2)