"""
Clockwork — Agent Handoff System
brief_generator.py: Renders the human-readable next_agent_brief.md.
"""

from __future__ import annotations

from .models import HandoffData


_TEMPLATE = """\
# Clockwork Agent Handoff Brief

---

## Project Summary

{current_summary}

---

## Next Task

{next_task}

---

## Skills Required

{skills_list}

---

## Frameworks & Languages

**Frameworks:** {frameworks}
**Languages:** {languages}

---

## Architecture

{architecture}

---

## Task State

{task_state}

---

## Rules

Follow repository rules defined in `{rules_reference}`.

---

*Generated by Clockwork on {generated_at}*
"""


def render_brief(data: HandoffData) -> str:
    """
    Render a Markdown agent brief from HandoffData.

    Args:
        data: Populated HandoffData instance.

    Returns:
        Markdown string ready to be written to next_agent_brief.md.
    """
    skills_list = "\n".join(f"- {s}" for s in data.skills_required) or "- Not specified"
    frameworks = ", ".join(data.frameworks) or "Not detected"
    languages = ", ".join(data.languages) or "Not detected"

    return _TEMPLATE.format(
        current_summary=data.current_summary,
        next_task=data.next_task,
        skills_list=skills_list,
        frameworks=frameworks,
        languages=languages,
        architecture=data.architecture,
        task_state=data.task_state,
        rules_reference=data.rules_reference,
        generated_at=data.generated_at,
    )